### ISSUE TITLE
Spec Flattening For Equivalent KVP Templates

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#13]
We do not currently flatten specs for structures that look like this, but we could.

For example:

```YAML
"key#foo":
  spec:  #equal to spec below
  value:
"key^foo":
  spec:  #equal to spec above
  value:
```

Could be flattened to:

 ```YAML
key:
  spec:
  "value#foo":
  "value^foo":
```
