### ISSUE TITLE
Value Templates Inside Array Item Template

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#42]
I expect the following template to work, however it does not work.

```yml
array:
  - "@arrayVar":
      "#boolVar":
        label: Truthy
      "^boolVar":
        label: Falsey
```

Converting the `boolVar` templates from value templates to key/value templates with an arbitrary key seems to be the only work around with the undesirable side effect of adding meaningless and unnecessary nesting/structure.

**Comment by ansongoldade** [comment]
I just tested this out with the updated syntax and processing logic and it produces what I think is the expected output. Using your template with the following data file.
```
arrayVar:
  - boolVar: true
  - boolVar: false
  - boolVar: true
```
I get the following output.
```
{
  "array": [
    {
      "label": "Truthy"
    },
    {
      "label": "Falsey"
    },
    {
      "label": "Truthy"
    }
  ]
}
```
