### ISSUE TITLE
Potential flattening issue

### ISSUE THREAD

**Issue by ansongoldade** [lynx-json/lynx-docs#86]
Need to further investigate, but the following template
```yaml
>content:
  data:
    realm: http://somerealm/
    >text: A Message
```
Resulted in the following JSON
```json
{
  "data": {
    "realm": "http://somerealm/",
    "spec": "a spec value",
    null 
  }
}
```
It appears the value portion was flattened but that is not valid when the value is `null`.
