### ISSUE TITLE
Extend Mime Map for `start`

### ISSUE THREAD

**Issue by danmork** [lynx-json/lynx-docs#91]
It would be nice to be able to extend lynx-docs with knowledge of additional media types. For example, in `.lynxdocsrc`:

```yaml
start:
  mime:
    'application/vnd.mycompany.mytype':
      - 'my-file-extension-1'
      - 'my-file-extension-2'
```

The structure above was stolen from and maps to the `mime` package's `define` function.
